baseURL = "/mb"
languageCode = "zh-CN"
title = "程序猫大刚"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 100

# disqusShortname = "mango-mb"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "程序猫大刚"

[params]
  author = "程序猫大刚"
  subtitle = "记录点滴，回头思过往！"
  keywords = "mango,mango mei,梦来梦网,芒果笔记,程序猫,猫大刚"
  description = "程序猫的个人博客，用来记录工作，生活，技术中的点点滴滴"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索
  beian = "粤ICP备17082965号"
  fancybox = true
  cdnJsSite = "cdn.bootcdn.net"

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "飞雪无情的博客"
  name = "飞雪无情的博客"
  url = "https://www.flysnow.org/"

[[params.links]]
  title = "闲心"
  name = "闲心"
  url = "http://sentsin.com/"

[[params.links]]
  title = "前端小武"
  name = "前端小武"
  url = "https://xuexb.com/"

[[params.links]]
  title = "大威"
  name = "大威"
  url = "http://blog.wayneww.top/"

## 侧边栏广告位
##[[params.ads]]
##  title = "【2019双12】ALL IN CLoud 低至1折"
##  url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
##  img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"
##[[params.ads]]
##  title = "助力产业智慧升级，云服务器首年88元起，更有千元代金券礼包免费领！"
##  url = "https://cloud.tencent.com/act/cps/redirect?redirect=1048&cps_key=14ff722692ac784fa8c3301c8c28d924&from=console"
##  img = "https://upload-dianshi-1255598498.file.myqcloud.com/345-7c71532bd4935fbdd9a67c1a71e577b1767b805c.200%E7%89%88%E6%9C%ACB.jpg"
##[[params.ads]]
##  title = "【渠道专享低折扣】11月特惠 限时2折"
##  url = "https://www.aliyun.com/acts/limit-buy?userCode=jdg9oj97"
##  img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"

[params.waline]
    enable = true
    placeholder = "说点什么吧..."
    serverURL = "https://valine-m1uexx7dk-mg0324.vercel.app" #换成你的serverURL
    serverURLGithub = "https://valine-mg0324.vercel.app/"


## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = false
  repo = "your github repo" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
##[params.cc]
##    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
##    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单
[menu]

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "pr"
    name = "发布日记"
    url = "/pr/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "http://mg.meiflower.top"
    weight = 4
